https://github.com/metanorma/metanorma-standoc/issues/785
metanorma/metanorma.org pull request #720
Opened 2023-06-06 14:18 UTC by opoudjis

### Metanorma PR checklist

 - [ ] Breaking changes (list related PRs)
 - [ ] Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] Gem with native library introduced

2024-02-11 07:20 UTC, ronaldtse commented
@kwkwan please take note of the latest changes from @opoudjis .

2024-02-21 01:25 UTC, ronaldtse commented
@kwkwan can you please fix the link checker job here and merge the changes? Thanks.

2024-02-21 04:48 UTC, ronaldtse requested changes
For the navigation links that are missing, let's comment them out first, and merge this.

2024-02-21 04:48 UTC, ronaldtse commented on _layouts/tutorial.html
> +          path: /tutorials/template/
@kwkwan can you please help fill these in?

2024-03-02 08:03 UTC, ronaldtse commented
Frankly I am not happy with the many "merges" across branches of this PR. 

But it's going to take too much time to rebase cleanly. Merging now.

2024-03-02 08:04 UTC, merged

2024-03-02 14:33 UTC, opoudjis commented
Sound version management practice presupposes that 40 PRs do not go unactioned for over a year. Hopefully this does not happen again.