Fix broken links in IHO related pages
metanorma/metanorma.org pull request #790
Opened 2024-07-03 08:20 UTC by kwkwan

### Metanorma PR checklist

 - [ ] Breaking changes (list related PRs)
 - [ ] Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] Gem with native library introduced

2024-07-03 08:32 UTC, ronaldtse requested changes

2024-07-04 00:28 UTC, kwkwan commented on author/iho/authoring-guide/bibliographic-references.adoc
> +. Cite a particular locality of the document, by cross-referencing the anchor name but additionally specify a link:/author/topics/document-format/xrefs/#localities[locality] as the second argument, l
@ronaldtse Should I change all `IHO 528-2019` to `IEEE 528-2019`?

2024-07-04 04:24 UTC, ronaldtse commented on author/iho/authoring-guide/bibliographic-references.adoc
> +. Cite a particular locality of the document, by cross-referencing the anchor name but additionally specify a link:/author/topics/document-format/xrefs/#localities[locality] as the second argument, l
Well, we should actually change the example completely to an IHO example. You can find the IHO publications at https://github.com/relaton/relaton-data-iho.

2024-07-04 04:25 UTC, ronaldtse approved these changes
Let's merge this first, then update the IHO publication. Thanks @kwkwan !

2024-07-04 04:25 UTC, merged